language: dart
sudo: required
dist: trusty
# dart version mapped to flutter channel
dart:
  - stable
  - dev
before_script:
  - pub run tekartik_travis_ci_flutter:install
  - source $(pub run tekartik_travis_ci_flutter:env)
script:
  - pub upgrade
  - dart tool/travis.dart
